var defaultItemGrid = [
    [
        "Ocarina",
        "Bow",
        "FireArrow",
        "IceArrow",
        "LightArrow",
    ],
    [
        "Bomb",
        "Bombchu",
        "DekuStick",
        "DekuNut",
        "MagicBean",
    ],
    [
        "PowderKeg",
        "PictographBox",
        "LensOfTruth",
        "Hookshot",
        "GreatFairySword",
    ],
    [
        "MoonsTear",
        "LandDeed",
        "SwampDeed",
        "MountainDeed",
        "OceanDeed",
        "ScarecrowSong",
    ],
    [
        "RoomKey",   
        "LetterToKafei",
        "PendantOfMemories",
        "LetterToMama",
        "HeartPieces",
        "HeartContainer",
    ],
    [
        "RedPotion",
        "GoldDust",
        "Milk",
        "ChateauRomani",
        "MysteryMilk",
        "EmptyBottle",
        "ZoraEgg",
    ],
    [
        "PostmanHat",
        "AllNightMask",
        "BlastMask",
        "StoneMask",
        "GreatFairyMask",
        "DekuMask",
    ],
    [
        "KeatonMask",
        "BremenMask",
        "BunnyHood",
        "DonGeroMask",
        "MaskOfScents",
        "GoronMask",
    ],
    [
        "RomaniMask",
        "TroupeLeaderMask",
        "KafeiMask",
        "CouplesMask",
        "MaskOfTruth",
        "ZoraMask"
    ],
    [
        "KamaroMask",
        "GibdoMask",
        "GaroMask",
        "CaptainsHat",
        "GiantsMask",
        "FierceDeityMask",
    ],
    [
        "Sword",
        "HeroShield",
        "MirrorShield",
        "OdolwaRemains",
        "GohtRemains",
        "GyorgRemains",
        "TwinmoldRemains",
    ],
    [
        "Magic",
        "BombersNotebook",
        "NoteNumOne",
        "NoteNumTwo",
        "NoteNumThree",
        "NoteNumFour",
        "NoteNumFive",
    ],
    [
        "SwampSkulltulas",
        "OceanSkulltulas",
        "TownStrayFairy",
        "SwampStrayFairy",
        "SnowStrayFairy",
        "OceanStrayFairy",
        "StoneStrayFairy",
    ],
    [
        "SwampMap",
        "SwampCompass",
        "SwampSmallKey",
        "SwampBigKey",
    ],
    [
        "SnowMap",
        "SnowCompass",
        "SnowSmallKey",
        "SnowBigKey",
    ],
    [
        "OceanMap",
        "OceanCompass",
        "OceanSmallKey",
        "OceanBigKey",
    ],
    [
        "StoneMap",
        "StoneCompass",
        "StoneSmallKey",
        "StoneBigKey",
    ],
    [
        "SongOfTime",
        "SongOfHealing",
        "SongOfSoaring",
        "EponasSong",
        "SongOfStorms",
    ],
    [
        "SonataOfAwakening",
        "GoronLullaby",
        "NewWaveBossaNova",
        "ElegyOfEmptiness",
        "OathToOrder",
    ]
];

var baseItems = {
    Ocarina: false,
    Bow: 0,
    FireArrow: false,
    IceArrow: false,
    LightArrow: false,

    Bomb: 0,
    Bombchu: false,
    DekuStick: false,
    DekuNut: false,
    MagicBean: false,

    PowderKeg: false,
    PictographBox: false,
    LensOfTruth: false,
    Hookshot: false,
    GreatFairySword: false,

    MoonsTear: false,
    LandDeed: false,
    SwampDeed: false,
    MountainDeed: false,
    OceanDeed: false,

    RoomKey: false,
    LetterToKafei: false,
    PendantOfMemories: false,
    LetterToMama: false,
    HeartPieces: 0,
    HeartContainer: 0,

    RedPotion: false,
    GoldDust: false,
    Milk: false,
    ChateauRomani: false,
    MysteryMilk: false,
    EmptyBottle: 0,
    ZoraEgg: 0,

    PostmanHat: false,
    AllNightMask: false,
    BlastMask: false,
    StoneMask: false,
    GreatFairyMask: false,
    DekuMask: false,

    KeatonMask: false,
    BremenMask: false,
    BunnyHood: false,
    DonGeroMask: false,
    MaskOfScents: false,
    GoronMask: false,

    RomaniMask: false,
    TroupeLeaderMask: false,
    KafeiMask: false,
    CouplesMask: false,
    MaskOfTruth: false,
    ZoraMask: false,

    KamaroMask: false,
    GibdoMask: false,
    GaroMask: false,
    CaptainsHat: false,
    GiantsMask: false,
    FierceDeityMask: false,

    Sword: 0,
    HeroShield: false,
    MirrorShield: false,
    OdolwaRemains: false,
    GohtRemains: false,
    GyorgRemains: false,
    TwinmoldRemains: false,

    Magic: 0,
    BombersNotebook: false,
    NoteNumOne: 0,
    NoteNumTwo: 0,
    NoteNumThree: 0,
    NoteNumFour: 0,
    NoteNumFive: 0,

    SwampSkulltulas: 0,
    OceanSkulltulas: 0,
    TownStrayFairy: false,
    SwampStrayFairy: 0,
    SnowStrayFairy: 0,
    OceanStrayFairy: 0,
    StoneStrayFairy: 0,

    SwampMap: false,
    SwampCompass: false,
    SwampSmallKey: 0,
    SwampBigKey: false,

    SnowMap: false,
    SnowCompass: false,
    SnowSmallKey: 0,
    SnowBigKey: false,
    
    OceanMap: false,
    OceanCompass: false,
    OceanSmallKey: 0,
    OceanBigKey: false,

    StoneMap: false,
    StoneCompass: false,
    StoneSmallKey: 0,
    StoneBigKey: false,

    SongOfTime: true,
    SongOfHealing: false,
    SongOfSoaring: false,
    EponasSong: false,
    SongOfStorms: false,
    
    SonataOfAwakening: false,
    GoronLullaby: false,
    NewWaveBossaNova: false,
    ElegyOfEmptiness: false,
    OathToOrder: false,

    blank: false,
    ScarecrowSong: true,
};

var itemsMin = {
    Bow: 0,
    Bomb: 0,
    HeartPieces: 0,
    HeartContainer: 0,
    EmptyBottle: 0,
    ZoraEggs: 0,
    Sword: 0,
    Magic: 0,
    NoteNum1: 0,
    NoteNum2: 0,
    NoteNum3: 0,
    NoteNum4: 0,
    NoteNum5: 0,
    SwampSkulltulas: 0,
    OceanSkulltulas: 0,
    SwampStrayFairy: 0,
    SnowStrayFairy: 0,
    OceanStrayFairy: 0,
    StoneStrayFairy: 0,
    SwampSmallKey: 0,
    SnowSmallKey: 0,
    OceanSmallKey: 0,
    StoneSmallKey: 0,
};

var itemsMax = {
    Bow: 3,
    Bomb: 3,
    HeartPieces: 48,
    HeartContainer: 4,
    EmptyBottle: 2,
    ZoraEggs: 6,
    Sword: 3,
    Magic: 2,
    NoteNum1: 5,
    NoteNum2: 5,
    NoteNum3: 5,
    NoteNum4: 5,
    NoteNum5: 5,
    SwampSkulltulas: 30,
    OceanSkulltulas: 30,
    SwampStrayFairy: 15,
    SnowStrayFairy: 15,
    OceanStrayFairy: 15,
    StoneStrayFairy: 15,
    SwampSmallKey: 1,
    SnowSmallKey: 3,
    OceanSmallKey: 1,
    StoneSmallKey: 4,
};

var items = Object.assign(baseItems);